{% set name = "keplergl" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52357af658ff21cf478b18e8670f9ee39c295dfdfe72a8f00cfcc523a7979962

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - jupyter
    - jupyter-packaging
    - pandas
    - geopandas
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.6.3
    - traittypes >=0.2.1
    - pandas >=1.3.1
    - geopandas >=0.9.0
    - shapely >=1.7.1
    - pyarrow >=16.0.0
    - geoarrow-pyarrow


test:
  requires:
    - python {{ python_min }}
  imports:
    - keplergl

about:
  home: https://github.com/keplergl/kepler.gl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Kepler.gl for Jupyter
  description: |
    This is a simple jupyter widget for kepler.gl, an advanced geospatial
    visualization tool, to render large-scale interactive maps.
  doc_url: https://docs.kepler.gl/docs/keplergl-jupyter

extra:
  recipe-maintainers:
    - lixun910
    - heshan0131
